# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ffa0ac83c636215ad95da7fd7eb49f62d65da873d62ae5c2adc1d67916b0c5a513d853db32fb55469e559833ef9d1253219eef68dd1d6e3cd909fd4bbcb2b18

test:
  secret_key_base: 1070df155cbb535209e344d2ef0fdd5ad0bc5aab06cca1b6005e66c99c99639cfcdace5029e3db042048cc3fe94630968b7d77c554699c078ebc01a17fd74272

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
